server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: market-service
  datasource:
    url: jdbc:h2:file:c:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

