server:
  port: ${APPLICATION_PORT:8080}

spring:
  spring:
    cloud:
      loadbalancer:
        ribbon:
          enable: false
  application:
    name: market-service
  datasource:
    url: jdbc:mysql://35.222.177.16:3306/db_market_service
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update



