server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: market-service
  datasource:
    url: jdbc:mysql://35.222.177.16:3306/db_market_service
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true


logging:
  level:
    org:
      hibernate:
        type: trace
